name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "1a54a1b0-fc89-4835-b5d8-a6f937698bd6"      # 替换为你创建的数据库 ID
